Wing clip no longer consumes Clever Strikes
wowsims/sod pull request #1052
Opened 2024-09-11 21:55 UTC by ncberman

![image](https://github.com/user-attachments/assets/74b58ab4-d174-42cc-a5f6-8f3bc28a1839)
Most of this stuff has already been implemented or are bug fixes. Everything in the sim already works the way these patch notes are written except for the wing clip change (in this PR) and the fire frost specialization runes which I will update the hunter trap PR with

2024-09-11 22:04 UTC, kayla-glick commented on sim/hunter/hunter.go
> +	SpellCode_HunterWingClip
I think you need to apply this to the wing clip spell itself still?

2024-09-12 16:09 UTC, kayla-glick approved these changes

2024-09-12 18:55 UTC, kayla-glick requested changes
Wing clip will still consume the aura because of the `OnCastComplete`. I mentioned on Discord, but consider setting an `affectedSpells` array up in an `OnInit` and use that in the callbacks

2024-09-12 21:56 UTC, kayla-glick approved these changes

2024-09-12 22:00 UTC, ncberman commented
I'm going to double check functionality really quick, not sure there are any tests that use this set bonus

2024-09-13 03:01 UTC, kayla-glick approved these changes

2024-09-13 03:01 UTC, merged